spring:
  messages:
    encoding: UTF-8

  datasource:
    driverClassName: org.postgresql.Driver
    #driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host.docker.internal:5432/db
    username: postgres
    password: postgres
    initialization-mode: always

  sql:
    init:
      mode: always


  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true

logging:
  level:
    ROOT: ERROR
    ru.otus.spring.controller: DEBUG
server:
  port: 8081